### ISSUE TITLE
Da error al aplicar

### ISSUE THREAD

**Issue by alfrenovsky** [ralsina/xrandroll#1]
Current mode for eDP-1: 1920x1080
Changing eDP-1 to 1920x1080
Traceback (most recent call last):
  File "main.py", line 114, in do_apply
    cli = gen_xrandr_from_data(self.xrandr_info)
  File "main.py", line 20, in gen_xrandr_from_data
    mod_x, mod_y = [int(n) for n in mon["current_mode"].split("x")]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by ralsina** [comment]
Me podes pasar lo que imprime tu xrandr? Asi veo por que no lo parsea bien.

**Comment by ralsina** [comment]
Fixed
